rm(list=ls(all=TRUE)) #Clear the memory of variables from previous run.
# This is not called by knitr, because it's above the first chunk.
cat("\f") # clear console when working in RStudio

# ---- load-sources ------------------------------------------------------------
# Call `base::source()` on any repo file that defines functions needed below.  Ideally, no real operations are performed.

# ---- load-packages -----------------------------------------------------------
# Attach these packages so their functions don't need to be qualified: http://r-pkgs.had.co.nz/namespace.html#search-path
library(magrittr) #Pipes
library(utils)
library(httr)
library(dplyr)
loadNamespace("dplyr")
library(OECD) # see vignette https://cran.r-project.org/web/packages/OECD/vignettes/oecd_vignette_main.html
library(rsdmx)
# ---- declare-globals ---------------------------------------------------------
config <- config::get()

# ---- load-data ---------------------------------------------------------------
dataset_list <- OECD::get_datasets()
search_dataset("health", data = dataset_list)
search_dataset("population", data = dataset_list)

# ---- define-queries ---------------------

if( !fs::dir_exists(config$path_oecd_health_chapter) )
  fs::dir_create(config$path_oecd_health_chapter)

# Population
dataset <- "HISTPOP"
dstruc <- OECD::get_data_structure(dataset)
str(dstruc, max.level = 1)
query_url_SDMX <- "https://stats.oecd.org/restsdmx/sdmx.ashx/GetData/HISTPOP/AUS+AUT+BEL+CAN+CHL+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LVA+LTU+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+EU28+G20+OECD+WLD+NMEC+ARG+BRA+BGR+CHN+COL+CRI+HRV+CYP+IND+IDN+MLT+ROU+RUS+SAU+SGP+ZAF.W+M+T.TOTAL+0_4+05_9+10_14+15_19+20_24+25_29+30_34+35_39+40_44+45_49+50_54+55_59+60_64+65_69+70_74+75_79+80_84+85_OVER+50_OVER+LESS_20+15-64+20-64+65_OVER+65_OVER_SHARE+LESS_15_SHARE+15-24_SHARE+OAD15-64+TOTD20-64+15-64_SHARE+POP_GR/all?startTime=2008&endTime=2018"
data <- rsdmx::readSDMX(query_url_SDMX) %>% as.data.frame()
ls_population <- list(
  "name" = dataset
  ,"structure" = dstruc
  ,"url" = query_url_SDMX
  ,"data" = data
)
pryr::object_size(ls_population)
readr::write_rds(ls_population, fs::path(config$path_oecd_health_chapter, "population.rds"))



# Health Care Resources
dataset <- "HEALTH_REAC"
dstruc <- OECD::get_data_structure(dataset)
str(dstruc, max.level = 1)
query_url_SDMX <- "https://stats.oecd.org/restsdmx/sdmx.ashx/GetData/HEALTH_REAC/GEHE+GEHETHSM+HEPL+PHYS+PHYSMEDE+PHYSPAPS+PHYSREGP+PAGG+PAGGFEMM+PAGGFU35+PAGGF344+PAGGF454+PAGGF564+PAGGF65O+PAGGF75O+PAGGHOMM+PAGGMU35+PAGGM344+PAGGM454+PAGGM564+PAGGM65O+PAGGM75O+PAGGTOPY+PAGGTU35+PAGGT344+PAGGT454+PAGGT564+PAGGT65O+PAGGT75O+EMPL+EMPLGENE+EMPLGENP+EMPLOTGP+EMPLSPMP+EMPLPEDI+EMPLGYNE+EMPLPSYS+EMPLSPEC+EMPLSURG+EMPLOTSP+EMPLOTPH+MIDW+MIDWMIDW+MIDWMIPA+MIDWMILP+MINU+MINUINFI+MINUQUAL+MINUASSO+MINUPANU+MINUPAPN+MINUPAAP+MINUNULP+MINULPPN+MINULPAP+CARE+CARECPRA+CARECPRO+DNST+DNSTDENT+DNSTPADN+DNSTLPDN+PHST+PHSTPHAR+PHSTPAPH+PHSTLPPH+PSIO+PSIOPHTH+HOEM+HOEMHEMP+HOEMHPHY+HOEMHNUR+HOEMHASN+HOEMHHCA+HOEMHOTH+HOEMHOTS+HEDU+HEDUMEGR+HEDUDNGR+HEDUPHGR+HEDUMWGR+HEDUNUGR+HEDUPNGR+HEDUAPGR+RVNU+RVNURMEG+RVNURMED+RVNURINF+HEPT+HOSP+HOSPTHOS+HOSPPUHO+HOSPNPHO+HOSPFRHO+HOSPGHOS+HOPI+HOPITBED+HOPILICS+HOPIREHA+HOPILIMM+HOPIOBED+HOPILIPS+HOPITPOH+HOPINROH+HOPIFROH+IPIN+IPINSCAN+IPINSCAH+IPINSCAA+IPINMRIM+IPINMRIH+IPINMRIA+IPINPETS+IPINPETH+IPINPETA+IPINGAMA+IPINGAMH+IPINGACA+IPINMAMO+IPINMAMH+IPINMAMA+IPINRTEQ+IPINRTEH+IPINRTEA.PERSMYNB+DENSPPNB+PEREMPNB+PHYTOTNB+PHYU35NB+PHY344NB+PHY454NB+PHY564NB+PHYT65NB+PHYT75NB+MILBIRNB+PERMEDNB+FTEEMPEF+DENSEFEF+PTHEMPNB+PFHEMPEF+NOMBRENB+PERPHYNB+YSALARMT+YSALXRMT+YSALPPMT+YSALGDMT+YSELFPMB+YSEFXRMB+YSEFPPMB+YSEFGDMB+NBMILPNB+HOPRAT+HOPFTE+NURRAT+NURFTE+LTCOVRNB+RTOINPNB+RTOALLNB+YSALAWMT+YSEFAWMT+YSALPIMT+YSEFPIMT.AUS+AUT+BEL+CAN+CHL+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LVA+LTU+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+NMEC+BRA+CHN+COL+CRI+IND+IDN+RUS+ZAF/all?startTime=2015&endTime=2018"
data <- rsdmx::readSDMX(query_url_SDMX) %>% as.data.frame()

ls_health_resources <- list(
  "name" = dataset
  ,"structure" = dstruc
  ,"url" = query_url_SDMX
  ,"data" = data
)
pryr::object_size(ls_health_resources)
readr::write_rds(ls_health_resources, fs::path(config$path_oecd_health_chapter, "health_resources.rds"))


# Health Status
dataset <- "HEALTH_STAT"
dstruc <- OECD::get_data_structure(dataset)
# str(dstruc, max.level = 1)
query_url_SDMX <- "https://stats.oecd.org/restsdmx/sdmx.ashx/GetData/HEALTH_STAT/EVIE+EVIEFE00+EVIEFE40+EVIEFE60+EVIEFE65+EVIEFE80+EVIEHO00+EVIEHO40+EVIEHO60+EVIEHO65+EVIEHO80+EVIETOTA+CICD+CICDALLC+CICDINFE+CICDTBLS+CICDHIVD+CICDNEOP+CICDTUME+CICDCANC+CICDNCRA+CICDMNBR+CICDSTOM+CICDPANC+CICDMNPR+CICDLIVR+CICDCRVX+CICDOVRY+CICDHODG+CICDLEUK+CICDBLAD+CICDSKIN+CICDSANG+CICDENDO+CICDDBTM+CICDTROU+CICDDMTA+CICDALCO+CICDSUBS+CICDNERV+CICDPARK+CICDALZH+CICDCIRC+CICDISCH+CICDMYOC+CICDCERV+CICDREPS+CICDINPN+CICDPNEU+CICDBAEM+CICDASMA+CICDDIGE+CICDPEPT+CICDCIRR+CICDPEAU+CICDOSTE+CICDGENI+CICDGROS+CICDAFFE+CICDCONG+CICDSYMP+CICDEXTC+CICDACCD+CICDTRAC+CICDCHUT+CICDPOSN+CICDHARM+CICDHOCD+MATI+MATIINFA+MATIINTW+MATINEON+MATINETW+MATIPERI+MATIMATM+PLYL+PLYLALLC+PLYLINFE+PLYLTBLS+PLYLHIVD+PLYLNEOP+PLYLTUME+PLYLCANC+PLYLNCRA+PLYLMNBR+PLYLSTOM+PLYLPANC+PLYLMNPR+PLYLLIVR+PLYLCRVX+PLYLOVRY+PLYLHODG+PLYLLEUK+PLYLBLAD+PLYLSKIN+PLYLSANG+PLYLENDO+PLYLDBTM+PLYLTROU+PLYLDMTA+PLYLALCO+PLYLSUBS+PLYLNERV+PLYLPARK+PLYLALZH+PLYLCIRC+PLYLISCH+PLYLMYOC+PLYLCERV+PLYLREPS+PLYLINPN+PLYLPNEU+PLYLBAEM+PLYLASMA+PLYLDIGE+PLYLPEPT+PLYLCIRR+PLYLPEAU+PLYLOSTE+PLYLGENI+PLYLGROS+PLYLAFFE+PLYLCONG+PLYLSYMP+PLYLEXTC+PLYLACCD+PLYLTRAC+PLYLCHUT+PLYLPOSN+PLYLHARM+PLYLHOCD+AVDM+AVDMPRVM+AVDMTRTM+PRHS+PRHSFGHE+PRHSFFAH+PRHSFBAH+PRHSMGHE+PRHSMFAH+PRHSMBAH+PRHSTGHE+PRHSTFAH+PRHSTBAH+SRHS+SRHSFGHA+SRHSFGHB+SRHSFGHC+SRHSFGHD+SRHSFGHE+SRHSMGHA+SRHSMGHB+SRHSMGHC+SRHSMGHD+SRHSMGHE+SRHSTGHA+SRHSTGHB+SRHSTGHC+SRHSTGHD+SRHSTGHE+SREC+SRECGHQO+SRECGHQV+SRECFE02+SRECFE34+SRECFE56+SRECMA02+SRECMA34+SRECMA56+SRECTO02+SRECTO34+SRECTO56+INFA+INFAPREM+COMD+COMDAIDS+COMDIPER+COMDIMEA+COMDIHPB+CANC+CANCTOCA+CANCCOLC+CANCLUNC+CANCBREC+CANCCEIX+CANCPROC+INJR+INJRACIR+DISA+DISASRAB+DISACPAB.EVIDUREV+EVIFHOEV+EVIHFEEV+NBFEMEPF+NBMALEPH+NBPOPUPC+TXCRUDTF+TXCRUDTH+TXCRUDTX+TXCMFETF+TXCMHOTH+TXCMILTX+RATEPTTX+TXMILBTH+TXCMMMTX+ANNFEMTF+ANNHOMTH+ANNTOTTX+PERCALEF+LIVBRTTX+NEWCASTX+PERCMTTX+NBWOMAPF+NBMANYPH+NBPOPIPC+INCITFTF+INCITHTH+BLESSETX+JOUPANNB+NOMBRENB.AUS+AUT+BEL+CAN+CHL+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LVA+LTU+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+NMEC+BRA+CHN+COL+CRI+IND+IDN+RUS+ZAF/all?startTime=2015&endTime=2019"
data <- rsdmx::readSDMX(query_url_SDMX) %>% as.data.frame()

ls_health_status <- list(
  "name" = dataset
  ,"structure" = dstruc
  ,"url" = query_url_SDMX
  ,"data" = data
)
pryr::object_size(ls_health_status)
readr::write_rds(ls_health_status, fs::path(config$path_oecd_health_chapter, "health_status.rds"))

# joining to the metadata in dstruc object
# ds1 <- data %>%
  # dplyr::left_join(
  #   dstruc$VAR
  #   , by = c("VAR"="id")
  # ) %>%
  #
  # dplyr::left_join(
  #   dstruc$UNIT
  #   , by = c("UNIT" = "id")
  # )
#




