var_label_available <- c(
 "Practising caring personnel"
,"Professionally active caring personnel"
,"Practising dentists"
,"Dentists licensed to practice"
,"Professionally active dentists"
,"Generalist medical practitioners"
,"General practitioners"
,"Obstetricians and gynaecologists"
,"Other generalist (non-specialist) medical practitioners"
,"Medical doctors not further defined"
,"Other specialists not elsewhere classified"
,"General paediatricians"
,"Psychiatrists"
,"medical group of specialists"
,"Specialist medical practitioners"
,"Surgical group of specialists"
,"Total health and social employment"
,"Associate Professional nursing graduates"
,"Dentists graduates"
,"Medical graduates"
,"Midwives graduates"
,"Nursing graduates"
,"Pharmacists graduates"
,"Professional nursing graduates"
,"Associate nurses employed in hospitals"
,"Total hospital employment"
,"Health care assistants employed in hospitals"
,"Professional nurses and midwives employed in hospitals"
,"Other Health service providers employed in hospitals"
,"Other staff employed in hospitals"
,"Physicians employed in hospitals"
,"Beds in for-profit privately owned hospitals"
,"Curative (acute) care beds"
,"Long-term care beds"
,"Psychiatric care beds"
,"Beds in not-for-profit privately owned hospitals"
,"Other hospital beds"
,"Rehabilitative care beds"
,"Total hospital beds"
,"Beds in publicly owned hospitals"
,"For-profit privately owned hospitals"
,"General hospitals"
,"Not-for-profit privately owned hospitals"
,"Publicly owned hospitals"
,"Hospitals"
,"Gamma cameras, in ambulatory sector"
,"Gamma cameras, total"
,"Gamma cameras, in hospitals"
,"Mammographs, in ambulatory sector"
,"Mammographs, in hospitals"
,"Mammographs, total"
,"Magnetic Resonance Imaging units, in ambulatory sector"
,"Magnetic Resonance Imaging units, in hospitals"
,"Magnetic Resonance Imaging units, total"
,"Positron Emission Tomography (PET) scanners, in ambulatory sector"
,"Positron Emission Tomography (PET) scanners, in hospitals"
,"Positron Emission Tomography (PET) scanners, total"
,"Radiation therapy equipment, in ambulatory sector"
,"Radiation therapy equipment, in hospitals"
,"Radiation therapy equipment, total"
,"Computed Tomography scanners, in ambulatory sector"
,"Computed Tomography scanners, in hospitals"
,"Computed Tomography scanners, total"
,"Practising midwives"
,"Midwives licensed to practice"
,"Professionally active midwives"
,"Associate Professional nurses, practising"
,"Practising nurses"
,"Associate Professional nurses, licensed to practice"
,"Professional nurses, licensed to practice"
,"Nurses licensed to practice"
,"Associate Professional nurses, professionally active"
,"Professionally active nurses"
,"Professional nurses, professionally active"
,"Professional nurses, practising"
,"Female physicians aged 35-44 years old"
,"Female physicians aged 45-54 years old"
,"Female physicians aged 55-64 years old"
,"Female physicians aged 65-74 years old"
,"Female physicians aged 75 years old and over"
,"Total female physicians"
,"Female physicians under 35 years old"
,"Total male physicians"
,"Male physicians aged 35-44 years old"
,"Male physicians aged 45-54 years old"
,"Male physicians aged 55-64 years old"
,"Male physicians aged 65-74 years old"
,"Male physicians aged 75 years old and over"
,"Male physicians under 35 years old"
,"Total physicians aged 35-44 years old"
,"Total physicians aged 45-54 years old"
,"Total physicians aged 55-64 years old"
,"Total physicians aged 65-74 years old"
,"Total physicians aged 75 years old and over"
,"Total physicians"
,"Total physicians under 35 years old"
,"Pharmacists licensed to practice"
,"Professionally active pharmacists"
,"Practising pharmacists"
,"Practising physicians"
,"Professionally active physicians"
,"Physicians licensed to practice"
,"Practising physiotherapists"
,"Remuneration of hospital nurses"
,"Remuneration of specialists"
,"Remuneration of general practitioners"
)

unit_label_available <- c(
"Density per 1 000 population (head counts)"
,"Number of persons (head counts)"
,"% of physicians (head counts)"
,"Per 1 000 live births"
,"% of total civilian employment"
,"Number"
,"Per 100 000 population"
,"Per 1 000 practising physicians"
,"Density per 1 000 population (FTE)"
,"Full-time equivalent persons (FTE)"
,"% of total hospital employment (FTE)"
,"% of total hospital employment (head counts)"
,"Per 1 000 population"
,"Per 1 000 population aged 65 years old and over"
,"Hospital employment-to-bed ratio (FTE)"
,"Hospital employment-to-bed ratio (head counts)"
,"Nurse-to-bed ratio (FTE)"
,"Nurse-to-bed ratio (head counts)"
,"Per million population"
,"% of total physicians aged 35-44 years old (head counts)"
,"% of total physicians aged 45-54 years old (head counts)"
,"% of total physicians aged 55-64 years old (head counts)"
,"% of total physicians aged 65-74 years old (head counts)"
,"% of total physicians aged 75 years old and over (head counts)"
,"% of total physicians (head counts)"
,"% of total physicians under 35 years old (head counts)"
,"Salaried, annual income, NCU"
,"Salaried, income per average wage"
,"Salaried, income, /capita GDP"
,"Salaried, annual income, NCU at 2010 GDP price level"
,"Salaried, income, US$ PPP"
,"Salaried, income, US$ exchange rate"
,"Self-employed, income per average wage"
,"Self-employed, income, /capita GDP"
,"Self-employed, annual income, NCU at 2010 GDP price level"
,"Self-employed, income, US$ PPP"
,"Self-employed, income, US$ exchange rate"
,"Self-employed, annual income, NCU"
)

var_name_available <- c(
  "CARECPRA", "CARECPRO", "DNSTDENT", "DNSTLPDN", "DNSTPADN",
  "EMPLGENE", "EMPLGENP", "EMPLGYNE", "EMPLOTGP", "EMPLOTPH", "EMPLOTSP",
  "EMPLPEDI", "EMPLPSYS", "EMPLSPEC", "EMPLSPMP", "EMPLSURG", "GEHETHSM",
  "HEDUAPGR", "HEDUDNGR", "HEDUMEGR", "HEDUMWGR", "HEDUNUGR", "HEDUPHGR",
  "HEDUPNGR", "HOEMHASN", "HOEMHEMP", "HOEMHHCA", "HOEMHNUR", "HOEMHOTH",
  "HOEMHOTS", "HOEMHPHY", "HOPIFROH", "HOPILICS", "HOPILIMM", "HOPILIPS",
  "HOPINROH", "HOPIOBED", "HOPIREHA", "HOPITBED", "HOPITPOH", "HOSPFRHO",
  "HOSPGHOS", "HOSPNPHO", "HOSPPUHO", "HOSPTHOS", "IPINGACA", "IPINGAMA",
  "IPINGAMH", "IPINMAMA", "IPINMAMH", "IPINMAMO", "IPINMRIA", "IPINMRIH",
  "IPINMRIM", "IPINPETA", "IPINPETH", "IPINPETS", "IPINRTEA", "IPINRTEH",
  "IPINRTEQ", "IPINSCAA", "IPINSCAH", "IPINSCAN", "MIDWMIDW", "MIDWMILP",
  "MIDWMIPA", "MINUASSO", "MINUINFI", "MINULPAP", "MINULPPN", "MINUNULP",
  "MINUPAAP", "MINUPANU", "MINUPAPN", "MINUQUAL", "PAGGF344", "PAGGF454",
  "PAGGF564", "PAGGF65O", "PAGGF75O", "PAGGFEMM", "PAGGFU35", "PAGGHOMM",
  "PAGGM344", "PAGGM454", "PAGGM564", "PAGGM65O", "PAGGM75O", "PAGGMU35",
  "PAGGT344", "PAGGT454", "PAGGT564", "PAGGT65O", "PAGGT75O", "PAGGTOPY",
  "PAGGTU35", "PHSTLPPH", "PHSTPAPH", "PHSTPHAR", "PHYSMEDE", "PHYSPAPS",
  "PHYSREGP", "PSIOPHTH", "RVNURINF", "RVNURMED", "RVNURMEG"
)

unit_name_available <- c(
  "DENSPPNB", "PERSMYNB", "PERMEDNB", "MILBIRNB", "PEREMPNB",
  "NOMBRENB", "RTOALLNB", "PERPHYNB", "DENSEFEF", "FTEEMPEF", "PFHEMPEF",
  "PTHEMPNB", "RTOINPNB", "LTCOVRNB", "HOPFTE", "HOPRAT", "NURFTE",
  "NURRAT", "NBMILPNB", "PHY344NB", "PHY454NB", "PHY564NB", "PHYT65NB",
  "PHYT75NB", "PHYTOTNB", "PHYU35NB", "YSALARMT", "YSALAWMT", "YSALGDMT",
  "YSALPIMT", "YSALPPMT", "YSALXRMT", "YSEFAWMT", "YSEFGDMB", "YSEFPIMT",
  "YSEFPPMB", "YSEFXRMB", "YSELFPMB"
)
